import React from 'react';
export declare const useDropdown: () => {
    isFocused: boolean;
    onBlur: () => void;
    onFocus: () => void;
    isMenuOpen: boolean;
    setIsMenuOpen: (isOpen: boolean) => void;
    handleMouseOver: () => void;
    handleMouseLeave: () => void;
    dropdownRef: React.RefObject<React.ReactNode | HTMLElement> | null;
    setDropdownRef: (dropdownRef: React.RefObject<React.ReactNode | HTMLElement>) => void;
    triggerRef: React.RefObject<React.ReactNode | HTMLElement> | null;
    setTriggerRef: (buttonRef: React.RefObject<React.ReactNode | HTMLElement>) => void;
    menuRef: React.RefObject<React.ReactNode | HTMLElement> | null;
    setMenuRef: (menuRef: React.RefObject<React.ReactNode | HTMLElement>) => void;
    menuAlign: string | null;
    setMenuAlign: (align: string) => void;
    menuOrientationX: string | null;
    setMenuOrientationX: (orientation: string) => void;
    menuOrientationY: string | null;
    setMenuOrientationY: (orientation: string) => void;
    menuBoundsObject: DOMRect;
    setMenuBoundsObject: (obj: DOMRect) => void;
    triggerBoundsObject: DOMRect;
    setTriggerBoundsObject: (obj: DOMRect) => void;
    autoAdjust: boolean;
    setAutoAdjust: (autoAdjust: boolean) => void;
    id: string | null;
    setId: (id: string) => void;
    layoutContainer: null | (HTMLElement | React.ReactElement);
    setLayoutContainer: (element: HTMLElement | React.ReactElement) => void;
    hoverMode: boolean;
    setHoverMode: (hoverMode: boolean) => void;
};
type DropdownContextProviderProps = {
    children: React.ReactNode;
};
export declare const DropdownContextProvider: ({ children }: DropdownContextProviderProps) => import("react/jsx-runtime").JSX.Element;
export {};
//# sourceMappingURL=DropdownContext.d.ts.map